apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapx-api
  labels:
    app: snapx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapx-api
  template:
    metadata:
      labels:
        app: snapx-api
    spec:
      containers:
        - name: snapx-api
          image: kuronejiaoi/snapx-api:v11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: FFMPEG_PATH
              value: "/usr/bin/ffmpeg"
            - name: FFPROBE_PATH
              value: "/usr/bin/ffprobe"
            - name: YTDLP_PATH
              value: "/usr/local/bin/yt-dlp"
          volumeMounts:
            - name: temp-storage
              mountPath: /app/TempStorage
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: temp-storage
          emptyDir: {}
      restartPolicy: Always