apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapx-api
  labels:
    app: snapx-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snapx-api
  template:
    metadata:
      labels:
        app: snapx-api
    spec:
      containers:
      - name: snapx-api
        image: snapx-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: FFMPEG_PATH
          value: "ffmpeg"
        - name: FFPROBE_PATH
          value: "ffprobe"
        - name: YTDLP_PATH
          value: "yt-dlp"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: temp-storage
          mountPath: /app/TempStorage
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: temp-storage
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: snapx-api-service
  labels:
    app: snapx-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: snapx-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snapx-api-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
